# ============================================================
# CircleGuard — Kubernetes Secrets (Credenciales Centralizadas)
# Namespace  : ${NAMESPACE}
# Aplicar con: envsubst < secrets.yml | kubectl apply -f -
# ============================================================

apiVersion: v1
kind: Secret
metadata:
  name: circleguard-secrets
  namespace: ${NAMESPACE}
  labels:
    app: circleguard-secrets
    team: dream-team
type: Opaque
data:
  # admin (Base64)
  postgres-username: YWRtaW4=
  # password (Base64)
  postgres-password: cGFzc3dvcmQ=
  # neo4j (Base64)
  neo4j-username: bmVvNGo=
  # password (Base64)
  neo4j-password: cGFzc3dvcmQ=
  # neo4j/password (Base64)
  neo4j-auth: bmVvNGovcGFzc3dvcmQ=
  # admin (Base64)
  ldap-admin-password: YWRtaW4=
