spring:
  application:
    name: circleguard-gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://auth-service:8180
            predicates:
              - Path=/api/v1/auth/**
          - id: identity-service
            uri: http://identity-service:8083
            predicates:
              - Path=/api/v1/identities/**
          - id: form-service
            uri: http://form-service:8086
            predicates:
              - Path=/api/v1/surveys/**,/api/v1/questionnaires/**,/api/v1/attachments/**
          - id: promotion-service
            uri: http://promotion-service:8088
            predicates:
              - Path=/api/v1/mesh/**,/api/v1/circles/**,/api/v1/encounters/**,/api/v1/health/**,/api/v1/location/**,/api/v1/sessions/**,/api/v1/buildings/**,/api/v1/floors/**,/api/v1/access-points/**
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "my-super-secret-dev-key-32-chars-long-12345678"
  expiration: 3600000

qr:
  secret: "my-qr-secret-key-for-dev-1234567890"
  expiration: 300

server:
  port: 8087
